function export_BSpline_to_IGES(filename, BS)
% export_BSpline_to_IGES  将 B 样条曲面结构体导出为 IGES 文件 (Entity 128)
%
% 用法:
%   export_BSpline_to_IGES('blade.igs', BS)
%
% 输入:
%   filename — 输出文件路径 (字符串), 例如 'blade_suction.igs'
%   BS       — B 样条曲面结构体，需包含以下字段:
%                .u_degree              — U 向阶数
%                .v_degree              — V 向阶数
%                .num_of_ctrl_points_u  — U 向控制点数
%                .num_of_ctrl_points_v  — V 向控制点数
%                .u_knots               — U 向节点向量 (行向量)
%                .v_knots               — V 向节点向量 (行向量)
%                .control_points_array  — (n_cp × 3) 控制点矩阵
%                                         按 U 优先顺序排列:
%                                         内层循环 U (i=1..nu)
%                                         外层循环 V (j=1..nv)
%
% ─────────────────────────────────────────────────────────────

    fid = fopen(filename, 'w');
    
    % 提取曲面参数
    k1 = BS.num_of_ctrl_points_u - 1;
    k2 = BS.num_of_ctrl_points_v - 1;
    m1 = BS.u_degree;
    m2 = BS.v_degree;
    
    % 1. Start 段 (S)
    fprintf(fid, '%-72sS%7d\n', 'Generated by MATLAB B-Spline Exporter', 1);
    
    % 2. Global 段 (G)
    % 包含分隔符、文件名、单位(MM)等基础信息
    g_str1 = '1H,,1H;,4HNONE,25HBlade_Suction_Surface.igs,';
    g_str2 = '10HMATLAB_GEN,10HMATLAB_GEN,32,38,6,38,15,';
    g_str3 = '25HBlade_Suction_Surface.igs,1.,2,2HMM,1,0.01,15H20260306.112057,';
    g_str4 = '0.0001,0.,10HMATLAB_USR,10HMATLAB_USR,11,0,15H20260306.112057;';
    
    fprintf(fid, '%-72sG%7d\n', g_str1, 1);
    fprintf(fid, '%-72sG%7d\n', g_str2, 2);
    fprintf(fid, '%-72sG%7d\n', g_str3, 3);
    fprintf(fid, '%-72sG%7d\n', g_str4, 4);
    
    % 3. Directory Entry 段 (D)
    % 实体 128 (NURBS 曲面)，分两行，每行 8 字符宽度对齐
    fprintf(fid, '%8d%8d%8d%8d%8d%8d%8d%8d10000000D%7d\n', 128, 1, 0, 0, 0, 0, 0, 0, 1);
    fprintf(fid, '%8d%8d%8d%8d%8d%8d%8d%8d00000000D%7d\n', 128, 0, 0, 1, 0, 0, 0, 0, 2);
    
    % 4. Parameter Data 段 (P)
    % 准备参数字符串 (实体 128 规范)
    % 属性: prop1=0(非闭合), prop2=0(非闭合), prop3=1(多项式,因为权重全为1), prop4=0(非周期), prop5=0(非周期)
    p_data = sprintf('128,%d,%d,%d,%d,0,0,1,0,0,', k1, k2, m1, m2);
    
    % 写入 U 和 V 节点
    p_data = [p_data, sprintf('%.6f,', BS.u_knots)];
    p_data = [p_data, sprintf('%.6f,', BS.v_knots)];
    
    % 写入权重 (全为 1)
    weights = ones(1, (k1+1)*(k2+1));
    p_data = [p_data, sprintf('%.1f,', weights)];
    
    % 写入控制点 (按 X,Y,Z 顺序)
    ctrl_pts = BS.control_points_array';
    p_data = [p_data, sprintf('%.6f,', ctrl_pts(:))];
    
    % 写入参数范围 (U0, U1, V0, V1) 并以分号结束
    p_data = [p_data, sprintf('%.6f,%.6f,%.6f,%.6f;', BS.u_knots(1), BS.u_knots(end), BS.v_knots(1), BS.v_knots(end))];
    
    % P 段需要每行最多 64 个字符，第 65-72 列是所属 D 段的指针
    p_lines = 0;
    ptr = 1;
    while ptr <= length(p_data)
        len = min(64, length(p_data) - ptr + 1);
        chunk = p_data(ptr : ptr+len-1);
        p_lines = p_lines + 1;
        % 左对齐填充至 64 位，后跟 D 段指针 (1)，然后 P 标识和行号
        fprintf(fid, '%-64s%8dP%7d\n', chunk, 1, p_lines);
        ptr = ptr + len;
    end
    
    % 5. Terminate 段 (T)
    % 记录 S, G, D, P 各段的行数
    fprintf(fid, 'S%7dG%7dD%7dP%7d%40sT%7d\n', 1, 4, 2, p_lines, '', 1);
    
    fclose(fid);
end